--Station
INSERT INTO [Amtrak.Station] VALUES ('ATN','Alabama','Anniston, AL','https://www.greatamericanstations.com/stations/anniston-al-atn/','AL')
INSERT INTO [Amtrak.Station] VALUES ('BHM','Alabama','Birmingham, AL','https://www.greatamericanstations.com/stations/birmingham-al-bhm/','AL')
INSERT INTO [Amtrak.Station] VALUES ('TCL','Alabama','Tuscaloosa, AL','https://www.greatamericanstations.com/stations/tuscaloosa-al-tcl/','AL')
INSERT INTO [Amtrak.Station] VALUES ('BEN','Arizona','Benson, AZ','https://www.greatamericanstations.com/stations/benson-az-ben/','AZ')
INSERT INTO [Amtrak.Station] VALUES ('FLG','Arizona','Flagstaff, AZ','https://www.greatamericanstations.com/stations/flagstaff-az-flg/','AZ')
INSERT INTO [Amtrak.Station] VALUES ('KNG','Arizona','Kingman, AZ','https://www.greatamericanstations.com/stations/kingman-az-kng/','AZ')
INSERT INTO [Amtrak.Station] VALUES ('MRC','Arizona','Maricopa, AZ','https://www.greatamericanstations.com/stations/maricopa-az-mrc/','AZ')
INSERT INTO [Amtrak.Station] VALUES ('TUS','Arizona','Tucson, AZ ','https://www.greatamericanstations.com/stations/tucson-az-tus/','AZ')
INSERT INTO [Amtrak.Station] VALUES ('WLO','Arizona','Winslow, AZ','https://www.greatamericanstations.com/stations/winslow-az-wlo/','AZ')
INSERT INTO [Amtrak.Station] VALUES ('YUM','Arizona','Yuma, AZ','https://www.greatamericanstations.com/stations/yuma-az-yum/','AZ')
INSERT INTO [Amtrak.Station] VALUES ('ARK','Arkansas','Arkadelphia, AR','https://www.greatamericanstations.com/stations/arkadelphia-ar-ark/','AR')
INSERT INTO [Amtrak.Station] VALUES ('HOP','Arkansas','Hope, AR','https://www.greatamericanstations.com/stations/hope-ar-hop/','AR')
INSERT INTO [Amtrak.Station] VALUES ('LRK','Arkansas','Little Rock, AR – Union Station','https://www.greatamericanstations.com/stations/little-rock-ar-lrk/','AR')
INSERT INTO [Amtrak.Station] VALUES ('MVN','Arkansas','Malvern, AR','https://www.greatamericanstations.com/stations/malvern-ar-mvn/','AR')
INSERT INTO [Amtrak.Station] VALUES ('TXA','Arkansas','Texarkana, AR','https://www.greatamericanstations.com/stations/texarkana-ar-txa/','AR')
INSERT INTO [Amtrak.Station] VALUES ('WNR','Arkansas','Walnut Ridge, AR','https://www.greatamericanstations.com/stations/walnut-ridge-ar-wnr/','AR')
INSERT INTO [Amtrak.Station] VALUES ('VAC','British Columbia (Canada)','Vancouver, BC – Pacific Central Station','https://www.greatamericanstations.com/stations/vancouver-bc-vac/','BC')
INSERT INTO [Amtrak.Station] VALUES ('ANA','California','Anaheim, CA – Regional Transportation Intermodal Center','https://www.greatamericanstations.com/stations/anaheim-ca-ana/','CA')
INSERT INTO [Amtrak.Station] VALUES ('ACA','California','Antioch-Pittsburg, CA','https://www.greatamericanstations.com/stations/antioch-pittsburg-ca-aca/','CA')
INSERT INTO [Amtrak.Station] VALUES ('ARN','California','Auburn, CA','https://www.greatamericanstations.com/stations/auburn-ca-arn/','CA')
INSERT INTO [Amtrak.Station] VALUES ('BFD','California','Bakersfield, CA','https://www.greatamericanstations.com/stations/bakersfield-ca-bfd/','CA')
INSERT INTO [Amtrak.Station] VALUES ('BAR','California','Barstow, CA – Harvey House Railroad Depot','https://www.greatamericanstations.com/stations/barstow-ca-bar/','CA')
INSERT INTO [Amtrak.Station] VALUES ('BKY','California','Berkeley, CA','https://www.greatamericanstations.com/stations/berkeley-ca-bky/','CA')
INSERT INTO [Amtrak.Station] VALUES ('BUR','California','Burbank—Airport, CA','https://www.greatamericanstations.com/stations/burbank-airport-ca-bur/','CA')
INSERT INTO [Amtrak.Station] VALUES ('BBK','California','Burbank—Downtown, CA','https://www.greatamericanstations.com/stations/burbank-ca-downtown-bbk/','CA')
INSERT INTO [Amtrak.Station] VALUES ('CML','California','Camarillo, CA','https://www.greatamericanstations.com/stations/camarillo-ca-cml/','CA')
INSERT INTO [Amtrak.Station] VALUES ('CPN','California','Carpinteria, CA','https://www.greatamericanstations.com/stations/carpinteria-ca-cpn/','CA')
INSERT INTO [Amtrak.Station] VALUES ('CWT','California','Chatsworth, CA','https://www.greatamericanstations.com/stations/chatsworth-ca-cwt/','CA')
INSERT INTO [Amtrak.Station] VALUES ('CIC','California','Chico, CA','https://www.greatamericanstations.com/stations/chico-ca-cic/','CA')
INSERT INTO [Amtrak.Station] VALUES ('COX','California','Colfax, CA','https://www.greatamericanstations.com/stations/colfax-ca-cox/','CA')
INSERT INTO [Amtrak.Station] VALUES ('COC','California','Corcoran, CA','https://www.greatamericanstations.com/stations/corcoran-ca-coc/','CA')
INSERT INTO [Amtrak.Station] VALUES ('DAV','California','Davis, CA','https://www.greatamericanstations.com/stations/davis-ca-dav/','CA')
INSERT INTO [Amtrak.Station] VALUES ('TRK','California','Denair, CA','https://www.greatamericanstations.com/stations/denair-ca-trk/','CA')
INSERT INTO [Amtrak.Station] VALUES ('DUN','California','Dunsmuir, CA','https://www.greatamericanstations.com/stations/dunsmuir-ca-dun/','CA')
INSERT INTO [Amtrak.Station] VALUES ('EMY','California','Emeryville, CA','https://www.greatamericanstations.com/stations/emeryville-ca-emy/','CA')
INSERT INTO [Amtrak.Station] VALUES ('FFV','California','Fairfield-Vacaville','https://www.greatamericanstations.com/stations/fairfield-vacaville-ca-ffv/','CA')
INSERT INTO [Amtrak.Station] VALUES ('FMT','California','Fremont, CA','https://www.greatamericanstations.com/stations/fremont-ca-fmt/','CA')
INSERT INTO [Amtrak.Station] VALUES ('FNO','California','Fresno, CA','https://www.greatamericanstations.com/stations/fresno-ca-fno/','CA')
INSERT INTO [Amtrak.Station] VALUES ('FUL','California','Fullerton, CA','https://www.greatamericanstations.com/stations/fullerton-ca-ful/','CA')
INSERT INTO [Amtrak.Station] VALUES ('GDL','California','Glendale, CA','https://www.greatamericanstations.com/stations/glendale-ca-gdl/','CA')
INSERT INTO [Amtrak.Station] VALUES ('GTA','California','Goleta, CA','https://www.greatamericanstations.com/stations/goleta-ca-gta/','CA')
INSERT INTO [Amtrak.Station] VALUES ('GVB','California','Grover Beach, CA','https://www.greatamericanstations.com/stations/grover-beach-ca-gvb/','CA')
INSERT INTO [Amtrak.Station] VALUES ('GUA','California','Guadalupe, CA','https://www.greatamericanstations.com/stations/guadalupe-ca-gua/','CA')
INSERT INTO [Amtrak.Station] VALUES ('HNF','California','Hanford, CA','https://www.greatamericanstations.com/stations/hanford-ca-hnf/','CA')
INSERT INTO [Amtrak.Station] VALUES ('HAY','California','Hayward, CA','https://www.greatamericanstations.com/stations/hayward-ca-hay/','CA')
INSERT INTO [Amtrak.Station] VALUES ('IRV','California','Irvine, CA','https://www.greatamericanstations.com/stations/irvine-ca-irv/','CA')
INSERT INTO [Amtrak.Station] VALUES ('LOD','California','Lodi, CA','https://www.greatamericanstations.com/stations/lodi-ca-lod/','CA')
INSERT INTO [Amtrak.Station] VALUES ('LPS','California','Lompoc-Surf, CA','https://www.greatamericanstations.com/stations/lompoc-surf-ca-lps/','CA')
INSERT INTO [Amtrak.Station] VALUES ('LAX','California','Los Angeles, CA – Union Station','https://www.greatamericanstations.com/stations/los-angeles-ca-lax/','CA')
INSERT INTO [Amtrak.Station] VALUES ('MDR','California','Madera, CA','https://www.greatamericanstations.com/stations/madera-ca-mdr/','CA')
INSERT INTO [Amtrak.Station] VALUES ('MTZ','California','Martinez, CA','https://www.greatamericanstations.com/stations/martinez-ca-mtz/','CA')
INSERT INTO [Amtrak.Station] VALUES ('MCD','California','Merced, CA','https://www.greatamericanstations.com/stations/merced-ca-mcd/','CA')
INSERT INTO [Amtrak.Station] VALUES ('MOD','California','Modesto, CA','https://www.greatamericanstations.com/stations/modesto-ca-mod/','CA')
INSERT INTO [Amtrak.Station] VALUES ('MPK','California','Moorpark, CA','https://www.greatamericanstations.com/stations/moorpark-ca-mpk/','CA')
INSERT INTO [Amtrak.Station] VALUES ('NDL','California','Needles, CA','https://www.greatamericanstations.com/stations/needles-ca-ndl/','CA')
INSERT INTO [Amtrak.Station] VALUES ('NRG','California','Northridge, CA','https://www.greatamericanstations.com/stations/northridge-ca-nrg/','CA')
INSERT INTO [Amtrak.Station] VALUES ('OKJ','California','Oakland, CA – Jack London Square Station','https://www.greatamericanstations.com/stations/oakland-jack-london-square-ca-okj/','CA')
INSERT INTO [Amtrak.Station] VALUES ('OAC','California','Oakland, CA – Coliseum / Airport','https://www.greatamericanstations.com/stations/oakland-coliseum-ca-oac/','CA')
INSERT INTO [Amtrak.Station] VALUES ('OSD','California','Oceanside, CA','https://www.greatamericanstations.com/stations/oceanside-ca-osd/','CA')
INSERT INTO [Amtrak.Station] VALUES ('ONA','California','Ontario, CA','https://www.greatamericanstations.com/stations/ontario-ca-ona/','CA')
INSERT INTO [Amtrak.Station] VALUES ('OXN','California','Oxnard, CA','https://www.greatamericanstations.com/stations/oxnard-ca-oxn/','CA')
INSERT INTO [Amtrak.Station] VALUES ('PSN','California','Palm Springs, CA','https://www.greatamericanstations.com/stations/palm-springs-ca-psn/','CA')
INSERT INTO [Amtrak.Station] VALUES ('PRB','California','Paso Robles, CA','https://www.greatamericanstations.com/stations/paso-robles-ca-prb/','CA')
INSERT INTO [Amtrak.Station] VALUES ('POS','California','Pomona, CA','https://www.greatamericanstations.com/stations/pomona-ca-pos/','CA')
INSERT INTO [Amtrak.Station] VALUES ('RDD','California','Redding, CA','https://www.greatamericanstations.com/stations/redding-ca-rdd/','CA')
INSERT INTO [Amtrak.Station] VALUES ('RIC','California','Richmond, CA','https://www.greatamericanstations.com/stations/richmond-ca-ric/','CA')
INSERT INTO [Amtrak.Station] VALUES ('RIV','California','Riverside, CA','https://www.greatamericanstations.com/stations/riverside-ca-riv/','CA')
INSERT INTO [Amtrak.Station] VALUES ('RLN','California','Rocklin, CA','https://www.greatamericanstations.com/stations/rocklin-ca-rln/','CA')
INSERT INTO [Amtrak.Station] VALUES ('RSV','California','Roseville, CA','https://www.greatamericanstations.com/stations/roseville-ca-rsv/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SAC','California','Sacramento, CA – Sacramento Valley Station','https://www.greatamericanstations.com/stations/sacramento-ca-sac/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SNS','California','Salinas, CA','https://www.greatamericanstations.com/stations/salinas-ca-sns/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SNB','California','San Bernardino, CA','https://www.greatamericanstations.com/stations/san-bernardino-ca-snb/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SNP','California','San Clemente Pier, CA','https://www.greatamericanstations.com/stations/san-clemente-ca-snp/','CA')
INSERT INTO [Amtrak.Station] VALUES ('OLT','California','San Diego, CA – Old Town Transportation Center','https://www.greatamericanstations.com/stations/san-diego-old-town-ca-olt/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SAN','California','San Diego, CA – Santa Fe Depot','https://www.greatamericanstations.com/stations/san-diego-ca-san/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SJC','California','San Jose, CA – Diridon Station','https://www.greatamericanstations.com/stations/san-jose-ca-sjc/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SNC','California','San Juan Capistrano, CA','https://www.greatamericanstations.com/stations/san-juan-capistrano-ca-snc/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SLO','California','San Luis Obispo, CA','https://www.greatamericanstations.com/stations/san-luis-obispo-ca-slo/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SNA','California','Santa Ana, CA','https://www.greatamericanstations.com/stations/santa-ana-ca-sna/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SBA','California','Santa Barbara, CA','https://www.greatamericanstations.com/stations/santa-barbara-ca-sba/','CA')
INSERT INTO [Amtrak.Station] VALUES ('GAC','California','Santa Clara, CA – Great America','https://www.greatamericanstations.com/stations/santa-clara-great-america-ca-gac/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SCC','California','Santa Clara, CA – Transit Center','https://www.greatamericanstations.com/stations/santa-clara-university-ca-scc/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SIM','California','Simi Valley, CA','https://www.greatamericanstations.com/stations/simi-valley-ca-sim/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SOL','California','Solana Beach, CA','https://www.greatamericanstations.com/stations/solana-beach-ca-sol/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SKT','California','Stockton, CA – Robert J. Cabral Station','https://www.greatamericanstations.com/stations/stockton-cabral-station-ca-skt/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SKN','California','Stockton, CA – San Joaquin Street Station','https://www.greatamericanstations.com/stations/stockton-san-joaquin-street-station-ca-skn/','CA')
INSERT INTO [Amtrak.Station] VALUES ('SUI','California','Suisun-Fairfield, CA','https://www.greatamericanstations.com/stations/suisun-fairfield-ca-sui/','CA')
INSERT INTO [Amtrak.Station] VALUES ('TRU','California','Truckee, CA','https://www.greatamericanstations.com/stations/truckee-ca-tru/','CA')
INSERT INTO [Amtrak.Station] VALUES ('VNC','California','Van Nuys, CA','https://www.greatamericanstations.com/stations/van-nuys-ca-vnc/','CA')
INSERT INTO [Amtrak.Station] VALUES ('VEC','California','Ventura, CA','https://www.greatamericanstations.com/stations/ventura-ca-vec/','CA')
INSERT INTO [Amtrak.Station] VALUES ('VRV','California','Victorville, CA','https://www.greatamericanstations.com/stations/victorville-ca-vrv/','CA')
INSERT INTO [Amtrak.Station] VALUES ('WAC','California','Wasco, CA','https://www.greatamericanstations.com/stations/wasco-ca-wac/','CA')
INSERT INTO [Amtrak.Station] VALUES ('DEN','Colorado','Denver, CO – Union Station','https://www.greatamericanstations.com/stations/denver-co-den/','CO')
INSERT INTO [Amtrak.Station] VALUES ('FMG','Colorado','Fort Morgan, CO','https://www.greatamericanstations.com/stations/fort-morgan-co-fmg/','CO')
INSERT INTO [Amtrak.Station] VALUES ('WIP','Colorado','Fraser-Winter Park, CO','https://www.greatamericanstations.com/stations/fraser-winter-park-co-wip/','CO')
INSERT INTO [Amtrak.Station] VALUES ('GSC','Colorado','Glenwood Springs, CO','https://www.greatamericanstations.com/stations/glenwood-springs-co-gsc/','CO')
INSERT INTO [Amtrak.Station] VALUES ('GRA','Colorado','Granby, CO','https://www.greatamericanstations.com/stations/granby-co-gra/','CO')
INSERT INTO [Amtrak.Station] VALUES ('GJT','Colorado','Grand Junction, CO','https://www.greatamericanstations.com/stations/grand-junction-co-gjt/','CO')
INSERT INTO [Amtrak.Station] VALUES ('LAJ','Colorado','La Junta, CO','https://www.greatamericanstations.com/stations/la-junta-co-laj/','CO')
INSERT INTO [Amtrak.Station] VALUES ('LMR','Colorado','Lamar, CO','https://www.greatamericanstations.com/stations/lamar-co-lmr/','CO')
INSERT INTO [Amtrak.Station] VALUES ('TRI','Colorado','Trinidad, CO','https://www.greatamericanstations.com/stations/trinidad-co-tri/','CO')
INSERT INTO [Amtrak.Station] VALUES ('WPR','Colorado','Winter Park, CO','https://www.greatamericanstations.com/stations/winter-park-co-wpr/','CO')
INSERT INTO [Amtrak.Station] VALUES ('BER','Connecticut','Berlin, CT','https://www.greatamericanstations.com/stations/berlin-ct-ber/','CT')
INSERT INTO [Amtrak.Station] VALUES ('BRP','Connecticut','Bridgeport, CT','https://www.greatamericanstations.com/stations/bridgeport-ct-brp/','CT')
INSERT INTO [Amtrak.Station] VALUES ('HFD','Connecticut','Hartford, CT','https://www.greatamericanstations.com/stations/hartford-ct-hfd/','CT')
INSERT INTO [Amtrak.Station] VALUES ('MDN','Connecticut','Meriden, CT','https://www.greatamericanstations.com/stations/meriden-ct-mdn/','CT')
INSERT INTO [Amtrak.Station] VALUES ('MYS','Connecticut','Mystic, CT','https://www.greatamericanstations.com/stations/mystic-ct-mys/','CT')
INSERT INTO [Amtrak.Station] VALUES ('NHV','Connecticut','New Haven, CT – Union Station','https://www.greatamericanstations.com/stations/new-haven-ct-nhv/','CT')
INSERT INTO [Amtrak.Station] VALUES ('STS','Connecticut','New Haven, CT – State Street Station','https://www.greatamericanstations.com/stations/new-haven-state-street-ct-sts/','CT')
INSERT INTO [Amtrak.Station] VALUES ('NLC','Connecticut','New London, CT – Union Station','https://www.greatamericanstations.com/stations/new-london-ct-nlc/','CT')
INSERT INTO [Amtrak.Station] VALUES ('OSB','Connecticut','Old Saybrook, CT','https://www.greatamericanstations.com/stations/old-saybrook-ct-osb/','CT')
INSERT INTO [Amtrak.Station] VALUES ('STM','Connecticut','Stamford, CT','https://www.greatamericanstations.com/stations/stamford-ct-stm/','CT')
INSERT INTO [Amtrak.Station] VALUES ('WFD','Connecticut','Wallingford, CT','https://www.greatamericanstations.com/stations/wallingford-ct-wfd/','CT')
INSERT INTO [Amtrak.Station] VALUES ('WNL','Connecticut','Windsor Locks, CT','https://www.greatamericanstations.com/stations/windsor-locks-ct-wnl/','CT')
INSERT INTO [Amtrak.Station] VALUES ('WND','Connecticut','Windsor, CT','https://www.greatamericanstations.com/stations/windsor-ct-wnd/','CT')
INSERT INTO [Amtrak.Station] VALUES ('NRK','Delaware','Newark, DE – Thomas R. Carper Station','https://www.greatamericanstations.com/stations/newark-de-nrk/','DE')
INSERT INTO [Amtrak.Station] VALUES ('WIL','Delaware','Wilmington, DE','https://www.greatamericanstations.com/stations/wilmington-de-wil/','DE')
INSERT INTO [Amtrak.Station] VALUES ('WAS','District of Columbia','Washington, DC – Union Station','https://www.greatamericanstations.com/stations/washington-union-station-dc-was/','DC')
INSERT INTO [Amtrak.Station] VALUES ('DFB','Florida','Deerfield Beach, FL','https://www.greatamericanstations.com/stations/deerfield-beach-fl-dfb/','FL')
INSERT INTO [Amtrak.Station] VALUES ('DLD','Florida','DeLand, FL','https://www.greatamericanstations.com/stations/deland-fl-dld/','FL')
INSERT INTO [Amtrak.Station] VALUES ('DLB','Florida','Delray Beach, FL','https://www.greatamericanstations.com/stations/delray-beach-fl-dlb/','FL')
INSERT INTO [Amtrak.Station] VALUES ('FTL','Florida','Fort Lauderdale, FL','https://www.greatamericanstations.com/stations/fort-lauderdale-fl-ftl/','FL')
INSERT INTO [Amtrak.Station] VALUES ('HOL','Florida','Hollywood, FL','https://www.greatamericanstations.com/stations/hollywood-fl-hol/','FL')
INSERT INTO [Amtrak.Station] VALUES ('JAX','Florida','Jacksonville, FL','https://www.greatamericanstations.com/stations/jacksonville-fl-jax/','FL')
INSERT INTO [Amtrak.Station] VALUES ('KIS','Florida','Kissimmee, FL','https://www.greatamericanstations.com/stations/kissimmee-fl-kis/','FL')
INSERT INTO [Amtrak.Station] VALUES ('LKL','Florida','Lakeland, FL (LAK ','https://www.greatamericanstations.com/stations/lakeland-fl-laklkl/','FL')
INSERT INTO [Amtrak.Station] VALUES ('MIA','Florida','Miami, FL','https://www.greatamericanstations.com/stations/miami-fl-mia/','FL')
INSERT INTO [Amtrak.Station] VALUES ('OKE','Florida','Okeechobee, FL','https://www.greatamericanstations.com/stations/okeechobee-fl-oke/','FL')
INSERT INTO [Amtrak.Station] VALUES ('ORL','Florida','Orlando, FL','https://www.greatamericanstations.com/stations/orlando-fl-orl/','FL')
INSERT INTO [Amtrak.Station] VALUES ('PAK','Florida','Palatka, FL','https://www.greatamericanstations.com/stations/palatka-fl-pak/','FL')
INSERT INTO [Amtrak.Station] VALUES ('SFA','Florida','Sanford, FL – Auto Train Station','https://www.greatamericanstations.com/stations/sanford-auto-train-fl-sfa/','FL')
INSERT INTO [Amtrak.Station] VALUES ('SBG','Florida','Sebring, FL','https://www.greatamericanstations.com/stations/sebring-fl-sbg/','FL')
INSERT INTO [Amtrak.Station] VALUES ('TPA','Florida','Tampa, FL – Union Station','https://www.greatamericanstations.com/stations/tampa-fl-tpa/','FL')
INSERT INTO [Amtrak.Station] VALUES ('WPB','Florida','West Palm Beach, FL','https://www.greatamericanstations.com/stations/west-palm-beach-fl-wpb/','FL')
INSERT INTO [Amtrak.Station] VALUES ('WTH','Florida','Winter Haven, FL','https://www.greatamericanstations.com/stations/winter-haven-fl-wth/','FL')
INSERT INTO [Amtrak.Station] VALUES ('WPK','Florida','Winter Park, FL','https://www.greatamericanstations.com/stations/winter-park-fl-wpk/','FL')
INSERT INTO [Amtrak.Station] VALUES ('ATL','Georgia','Atlanta, GA','https://www.greatamericanstations.com/stations/atlanta-ga-atl/','GA')
INSERT INTO [Amtrak.Station] VALUES ('GNS','Georgia','Gainesville, GA','https://www.greatamericanstations.com/stations/gainesville-ga-gns/','GA')
INSERT INTO [Amtrak.Station] VALUES ('JSP','Georgia','Jesup, GA','https://www.greatamericanstations.com/stations/jesup-ga-jsp/','GA')
INSERT INTO [Amtrak.Station] VALUES ('SAV','Georgia','Savannah, GA','https://www.greatamericanstations.com/stations/savannah-ga-sav/','GA')
INSERT INTO [Amtrak.Station] VALUES ('TCA','Georgia','Toccoa, GA','https://www.greatamericanstations.com/stations/toccoa-ga-tca/','GA')
INSERT INTO [Amtrak.Station] VALUES ('SPT','Idaho','Sandpoint, ID','https://www.greatamericanstations.com/stations/sandpoint-id-spt/','ID')
INSERT INTO [Amtrak.Station] VALUES ('ALN','Illinois','Alton, IL','https://www.greatamericanstations.com/stations/alton-il-aln/','IL')
INSERT INTO [Amtrak.Station] VALUES ('BNL','Illinois','Bloomington-Normal, IL','https://www.greatamericanstations.com/stations/normal-il-bnl/','IL')
INSERT INTO [Amtrak.Station] VALUES ('CDL','Illinois','Carbondale, IL','https://www.greatamericanstations.com/stations/carbondale-il-cdl/','IL')
INSERT INTO [Amtrak.Station] VALUES ('CRV','Illinois','Carlinville, IL','https://www.greatamericanstations.com/stations/carlinville-il-crv/','IL')
INSERT INTO [Amtrak.Station] VALUES ('CEN','Illinois','Centralia, IL','https://www.greatamericanstations.com/stations/centralia-il-cen/','IL')
INSERT INTO [Amtrak.Station] VALUES ('CHM','Illinois','Champaign – Urbana, IL','https://www.greatamericanstations.com/stations/champaign-urbana-il-chm/','IL')
INSERT INTO [Amtrak.Station] VALUES ('CHI','Illinois','Chicago, IL – Union Station','https://www.greatamericanstations.com/stations/chicago-il-chi/','IL')
INSERT INTO [Amtrak.Station] VALUES ('DQN','Illinois','Du Quoin, IL','https://www.greatamericanstations.com/stations/du-quoin-il-dqn/','IL')
INSERT INTO [Amtrak.Station] VALUES ('DWT','Illinois','Dwight, IL','https://www.greatamericanstations.com/stations/dwight-il-dwt/','IL')
INSERT INTO [Amtrak.Station] VALUES ('EFG','Illinois','Effingham, IL','https://www.greatamericanstations.com/stations/effingham-il-efg/','IL')
INSERT INTO [Amtrak.Station] VALUES ('GBB','Illinois','Galesburg, IL','https://www.greatamericanstations.com/stations/galesburg-il-gbb/','IL')
INSERT INTO [Amtrak.Station] VALUES ('GLM','Illinois','Gilman, IL','https://www.greatamericanstations.com/stations/gilman-il-glm/','IL')
INSERT INTO [Amtrak.Station] VALUES ('GLN','Illinois','Glenview, IL','https://www.greatamericanstations.com/stations/glenview-il-gln/','IL')
INSERT INTO [Amtrak.Station] VALUES ('HMW','Illinois','Homewood, IL','https://www.greatamericanstations.com/stations/homewood-il-hmw/','IL')
INSERT INTO [Amtrak.Station] VALUES ('JOL','Illinois','Joliet, IL','https://www.greatamericanstations.com/stations/joliet-il-jol/','IL')
INSERT INTO [Amtrak.Station] VALUES ('KKI','Illinois','Kankakee, IL','https://www.greatamericanstations.com/stations/kankakee-il-kki/','IL')
INSERT INTO [Amtrak.Station] VALUES ('KEE','Illinois','Kewanee, IL','https://www.greatamericanstations.com/stations/kewanee-il-kee/','IL')
INSERT INTO [Amtrak.Station] VALUES ('LAG','Illinois','La Grange, IL','https://www.greatamericanstations.com/stations/la-grange-il-lag/','IL')
INSERT INTO [Amtrak.Station] VALUES ('LCN','Illinois','Lincoln, IL','https://www.greatamericanstations.com/stations/lincoln-il-lcn/','IL')
INSERT INTO [Amtrak.Station] VALUES ('MAC','Illinois','Macomb, IL – Thomas C. Carper Station','https://www.greatamericanstations.com/stations/macomb-il-mac/','IL')
INSERT INTO [Amtrak.Station] VALUES ('MAT','Illinois','Mattoon, IL','https://www.greatamericanstations.com/stations/mattoon-il-mat/','IL')
INSERT INTO [Amtrak.Station] VALUES ('MDT','Illinois','Mendota, IL','https://www.greatamericanstations.com/stations/mendota-il-mdt/','IL')
INSERT INTO [Amtrak.Station] VALUES ('NPV','Illinois','Naperville, IL','https://www.greatamericanstations.com/stations/naperville-il-npv/','IL')
INSERT INTO [Amtrak.Station] VALUES ('PLO','Illinois','Plano, IL','https://www.greatamericanstations.com/stations/plano-il-plo/','IL')
INSERT INTO [Amtrak.Station] VALUES ('PON','Illinois','Pontiac, IL','https://www.greatamericanstations.com/stations/pontiac-il-pon/','IL')
INSERT INTO [Amtrak.Station] VALUES ('PCT','Illinois','Princeton, IL','https://www.greatamericanstations.com/stations/princeton-il-pct/','IL')
INSERT INTO [Amtrak.Station] VALUES ('QCY','Illinois','Quincy, IL','https://www.greatamericanstations.com/stations/quincy-il-qcy/','IL')
INSERT INTO [Amtrak.Station] VALUES ('RTL','Illinois','Rantoul, IL','https://www.greatamericanstations.com/stations/rantoul-il-rtl/','IL')
INSERT INTO [Amtrak.Station] VALUES ('SPI','Illinois','Springfield, IL','https://www.greatamericanstations.com/stations/springfield-il-spi/','IL')
INSERT INTO [Amtrak.Station] VALUES ('SMT','Illinois','Summit, IL','https://www.greatamericanstations.com/stations/summit-il-smt/','IL')
INSERT INTO [Amtrak.Station] VALUES ('COI','Indiana','Connersville, IN','https://www.greatamericanstations.com/stations/connersville-in-coi/','IN')
INSERT INTO [Amtrak.Station] VALUES ('CRF','Indiana','Crawfordsville, IN','https://www.greatamericanstations.com/stations/crawfordsville-in-crf/','IN')
INSERT INTO [Amtrak.Station] VALUES ('DYE','Indiana','Dyer, IN','https://www.greatamericanstations.com/stations/dyer-in-dye/','IN')
INSERT INTO [Amtrak.Station] VALUES ('EKH','Indiana','Elkhart, IN','https://www.greatamericanstations.com/stations/elkhart-in-ekh/','IN')
INSERT INTO [Amtrak.Station] VALUES ('HMI','Indiana','Hammond-Whiting, IN','https://www.greatamericanstations.com/stations/hammond-whiting-in-hmi/','IN')
INSERT INTO [Amtrak.Station] VALUES ('IND','Indiana','Indianapolis, IN','https://www.greatamericanstations.com/stations/indianapolis-in-ind/','IN')
INSERT INTO [Amtrak.Station] VALUES ('LAF','Indiana','Lafayette, IN','https://www.greatamericanstations.com/stations/lafayette-in-laf/','IN')
INSERT INTO [Amtrak.Station] VALUES ('REN','Indiana','Rensselaer, IN','https://www.greatamericanstations.com/stations/rensselaer-in-ren/','IN')
INSERT INTO [Amtrak.Station] VALUES ('SOB','Indiana','South Bend, IN','https://www.greatamericanstations.com/stations/south-bend-in-sob/','IN')
INSERT INTO [Amtrak.Station] VALUES ('WTI','Indiana','Waterloo, IN','https://www.greatamericanstations.com/stations/waterloo-in-wti/','IN')
INSERT INTO [Amtrak.Station] VALUES ('BRL','Iowa','Burlington, IA','https://www.greatamericanstations.com/stations/burlington-ia-brl/','IA')
INSERT INTO [Amtrak.Station] VALUES ('CRN','Iowa','Creston, IA','https://www.greatamericanstations.com/stations/creston-ia-crn/','IA')
INSERT INTO [Amtrak.Station] VALUES ('FMD','Iowa','Fort Madison, IA','https://www.greatamericanstations.com/stations/fort-madison-ia-fmd/','IA')
INSERT INTO [Amtrak.Station] VALUES ('MTP','Iowa','Mount Pleasant, IA','https://www.greatamericanstations.com/stations/mt-pleasant-ia-mtp/','IA')
INSERT INTO [Amtrak.Station] VALUES ('OSC','Iowa','Osceola, IA','https://www.greatamericanstations.com/stations/osceola-ia-osc/','IA')
INSERT INTO [Amtrak.Station] VALUES ('OTM','Iowa','Ottumwa, IA','https://www.greatamericanstations.com/stations/ottumwa-ia-otm/','IA')
INSERT INTO [Amtrak.Station] VALUES ('DDG','Kansas','Dodge City, KS','https://www.greatamericanstations.com/stations/dodge-city-ks-ddg/','KS')
INSERT INTO [Amtrak.Station] VALUES ('GCK','Kansas','Garden City, KS','https://www.greatamericanstations.com/stations/garden-city-ks-gck/','KS')
INSERT INTO [Amtrak.Station] VALUES ('HUT','Kansas','Hutchinson, KS','https://www.greatamericanstations.com/stations/hutchinson-ks-hut/','KS')
INSERT INTO [Amtrak.Station] VALUES ('LRC','Kansas','Lawrence, KS','https://www.greatamericanstations.com/stations/lawrence-ks-lrc/','KS')
INSERT INTO [Amtrak.Station] VALUES ('NEW','Kansas','Newton, KS','https://www.greatamericanstations.com/stations/newton-ks-new/','KS')
INSERT INTO [Amtrak.Station] VALUES ('TOP','Kansas','Topeka, KS','https://www.greatamericanstations.com/stations/topeka-ks-top/','KS')
INSERT INTO [Amtrak.Station] VALUES ('AKY','Kentucky','Ashland, KY','https://www.greatamericanstations.com/stations/ashland-ky-aky/','KY')
INSERT INTO [Amtrak.Station] VALUES ('FTN','Kentucky','Fulton, KY','https://www.greatamericanstations.com/stations/fulton-ky-ftn/','KY')
INSERT INTO [Amtrak.Station] VALUES ('MAY','Kentucky','Maysville, KY','https://www.greatamericanstations.com/stations/maysville-ky-may/','KY')
INSERT INTO [Amtrak.Station] VALUES ('SPM','Kentucky','South Shore, KY – Portsmouth, OH','https://www.greatamericanstations.com/stations/south-shore-ky-spm/','KY')
INSERT INTO [Amtrak.Station] VALUES ('HMD','Louisiana','Hammond, LA','https://www.greatamericanstations.com/stations/hammond-la-hmd/','LA')
INSERT INTO [Amtrak.Station] VALUES ('LFT','Louisiana','Lafayette, LA','https://www.greatamericanstations.com/stations/lafayette-la-lft/','LA')
INSERT INTO [Amtrak.Station] VALUES ('LCH','Louisiana','Lake Charles, LA','https://www.greatamericanstations.com/stations/lake-charles-la-lch/','LA')
INSERT INTO [Amtrak.Station] VALUES ('NIB','Louisiana','New Iberia, LA','https://www.greatamericanstations.com/stations/new-iberia-la-nib/','LA')
INSERT INTO [Amtrak.Station] VALUES ('NOL','Louisiana','New Orleans, LA – Union Passenger Terminal','https://www.greatamericanstations.com/stations/new-orleans-la-nol/','LA')
INSERT INTO [Amtrak.Station] VALUES ('SCH','Louisiana','Schriever, LA','https://www.greatamericanstations.com/stations/schriever-la-sch/','LA')
INSERT INTO [Amtrak.Station] VALUES ('SDL','Louisiana','Slidell, LA','https://www.greatamericanstations.com/stations/slidell-la-sdl/','LA')
INSERT INTO [Amtrak.Station] VALUES ('BRK','Maine','Brunswick, ME','https://www.greatamericanstations.com/stations/brunswick-me-brk/','ME')
INSERT INTO [Amtrak.Station] VALUES ('FRE','Maine','Freeport, ME','https://www.greatamericanstations.com/stations/freeport-me-fre/','ME')
INSERT INTO [Amtrak.Station] VALUES ('ORB','Maine','Old Orchard Beach, ME','https://www.greatamericanstations.com/stations/old-orchard-beach-me-orb/','ME')
INSERT INTO [Amtrak.Station] VALUES ('POR','Maine','Portland, ME','https://www.greatamericanstations.com/stations/portland-me-por/','ME')
INSERT INTO [Amtrak.Station] VALUES ('SAO','Maine','Saco, ME','https://www.greatamericanstations.com/stations/saco-biddeford-me-sao/','ME')
INSERT INTO [Amtrak.Station] VALUES ('WEM','Maine','Wells, ME','https://www.greatamericanstations.com/stations/wells-me-wem/','ME')
INSERT INTO [Amtrak.Station] VALUES ('ABE','Maryland','Aberdeen, MD','https://www.greatamericanstations.com/stations/aberdeen-md-abe/','MD')
INSERT INTO [Amtrak.Station] VALUES ('BAL','Maryland','Baltimore, MD – Penn Station','https://www.greatamericanstations.com/stations/baltimore-penn-station-md-bal/','MD')
INSERT INTO [Amtrak.Station] VALUES ('BWI','Maryland','Baltimore, MD – BWI Thurgood Marshall Airport','https://www.greatamericanstations.com/stations/bwi-airport-thurgood-marshall-airport-md-bwi/','MD')
INSERT INTO [Amtrak.Station] VALUES ('CUM','Maryland','Cumberland, MD','https://www.greatamericanstations.com/stations/cumberland-md-cum/','MD')
INSERT INTO [Amtrak.Station] VALUES ('NCR','Maryland','New Carrollton, MD','https://www.greatamericanstations.com/stations/new-carrollton-md-ncr/','MD')
INSERT INTO [Amtrak.Station] VALUES ('RKV','Maryland','Rockville, MD','https://www.greatamericanstations.com/stations/rockville-md-rkv/','MD')
INSERT INTO [Amtrak.Station] VALUES ('BBY','Massachusetts','Boston, MA – Back Bay Station','https://www.greatamericanstations.com/stations/boston-back-bay-ma-bby/','MA')
INSERT INTO [Amtrak.Station] VALUES ('BON','Massachusetts','Boston, MA – North Station','https://www.greatamericanstations.com/stations/boston-north-station-ma-bon/','MA')
INSERT INTO [Amtrak.Station] VALUES ('BOS','Massachusetts','Boston, MA – South Station','https://www.greatamericanstations.com/stations/boston-south-station-ma-bos/','MA')
INSERT INTO [Amtrak.Station] VALUES ('FRA','Massachusetts','Framingham, MA','https://www.greatamericanstations.com/stations/framingham-ma-fra/','MA')
INSERT INTO [Amtrak.Station] VALUES ('GFD','Massachusetts','Greenfield, MA','https://www.greatamericanstations.com/stations/greenfield-ma-gfd/','MA')
INSERT INTO [Amtrak.Station] VALUES ('HHL','Massachusetts','Haverhill, MA','https://www.greatamericanstations.com/stations/haverhill-ma-hhl/','MA')
INSERT INTO [Amtrak.Station] VALUES ('HLK','Massachusetts','Holyoke, MA','https://www.greatamericanstations.com/stations/holyoke-ma-hlk/','MA')
INSERT INTO [Amtrak.Station] VALUES ('NHT','Massachusetts','Northampton, MA','https://www.greatamericanstations.com/stations/northampton-ma-nht/','MA')
INSERT INTO [Amtrak.Station] VALUES ('PIT','Massachusetts','Pittsfield, MA','https://www.greatamericanstations.com/stations/pittsfield-ma-pit/','MA')
INSERT INTO [Amtrak.Station] VALUES ('RTE','Massachusetts','Route 128, MA','https://www.greatamericanstations.com/stations/route-128-ma-rte/','MA')
INSERT INTO [Amtrak.Station] VALUES ('SPG','Massachusetts','Springfield, MA','https://www.greatamericanstations.com/stations/springfield-ma-spg/','MA')
INSERT INTO [Amtrak.Station] VALUES ('WOB','Massachusetts','Woburn, MA','https://www.greatamericanstations.com/stations/woburn-ma-wob/','MA')
INSERT INTO [Amtrak.Station] VALUES ('WOR','Massachusetts','Worcester, MA – Union Station','https://www.greatamericanstations.com/stations/worcester-ma-wor/','MA')
INSERT INTO [Amtrak.Station] VALUES ('ALI','Michigan','Albion, MI','https://www.greatamericanstations.com/stations/albion-mi-ali/','MI')
INSERT INTO [Amtrak.Station] VALUES ('ARB','Michigan','Ann Arbor, MI','https://www.greatamericanstations.com/stations/ann-arbor-mi-arb/','MI')
INSERT INTO [Amtrak.Station] VALUES ('BAM','Michigan','Bangor, MI','https://www.greatamericanstations.com/stations/bangor-mi-bam/','MI')
INSERT INTO [Amtrak.Station] VALUES ('BTL','Michigan','Battle Creek, MI','https://www.greatamericanstations.com/stations/battle-creek-mi-btl/','MI')
INSERT INTO [Amtrak.Station] VALUES ('DER','Michigan','Dearborn, MI','https://www.greatamericanstations.com/stations/dearborn-mi-der/','MI')
INSERT INTO [Amtrak.Station] VALUES ('DET','Michigan','Detroit, MI','https://www.greatamericanstations.com/stations/detroit-mi-det/','MI')
INSERT INTO [Amtrak.Station] VALUES ('DOA','Michigan','Dowagiac, MI','https://www.greatamericanstations.com/stations/dowagiac-mi-doa/','MI')
INSERT INTO [Amtrak.Station] VALUES ('DRD','Michigan','Durand, MI','https://www.greatamericanstations.com/stations/durand-mi-drd/','MI')
INSERT INTO [Amtrak.Station] VALUES ('LNS','Michigan','East Lansing, MI','https://www.greatamericanstations.com/stations/east-lansing-mi-lns/','MI')
INSERT INTO [Amtrak.Station] VALUES ('FLN','Michigan','Flint, MI','https://www.greatamericanstations.com/stations/flint-mi-fln/','MI')
INSERT INTO [Amtrak.Station] VALUES ('GRR','Michigan','Grand Rapids, MI','https://www.greatamericanstations.com/stations/grand-rapids-mi-grr/','MI')
INSERT INTO [Amtrak.Station] VALUES ('HOM','Michigan','Holland, MI','https://www.greatamericanstations.com/stations/holland-mi-hom/','MI')
INSERT INTO [Amtrak.Station] VALUES ('JXN','Michigan','Jackson, MI','https://www.greatamericanstations.com/stations/jackson-mi-jxn/','MI')
INSERT INTO [Amtrak.Station] VALUES ('KAL','Michigan','Kalamazoo, MI','https://www.greatamericanstations.com/stations/kalamazoo-mi-kal/','MI')
INSERT INTO [Amtrak.Station] VALUES ('LPE','Michigan','Lapeer, MI','https://www.greatamericanstations.com/stations/lapeer-mi-lpe/','MI')
INSERT INTO [Amtrak.Station] VALUES ('NBU','Michigan','New Buffalo, MI','https://www.greatamericanstations.com/stations/new-buffalo-mi-nbu/','MI')
INSERT INTO [Amtrak.Station] VALUES ('NLS','Michigan','Niles, MI','https://www.greatamericanstations.com/stations/niles-mi-nls/','MI')
INSERT INTO [Amtrak.Station] VALUES ('PNT','Michigan','Pontiac, MI','https://www.greatamericanstations.com/stations/pontiac-mi-pnt/','MI')
INSERT INTO [Amtrak.Station] VALUES ('PTH','Michigan','Port Huron, MI','https://www.greatamericanstations.com/stations/port-huron-mi-pth/','MI')
INSERT INTO [Amtrak.Station] VALUES ('ROY','Michigan','Royal Oak, MI','https://www.greatamericanstations.com/stations/royal-oak-mi-roy/','MI')
INSERT INTO [Amtrak.Station] VALUES ('SJM','Michigan','St. Joseph-Benton Harbor, MI','https://www.greatamericanstations.com/stations/st-joseph-mi-sjm/','MI')
INSERT INTO [Amtrak.Station] VALUES ('TRM','Michigan','Troy, MI','https://www.greatamericanstations.com/stations/troy-mi-trm/','MI')
INSERT INTO [Amtrak.Station] VALUES ('DLK','Minnesota','Detroit Lakes, MN','https://www.greatamericanstations.com/stations/detroit-lakes-mn-dlk/','MN')
INSERT INTO [Amtrak.Station] VALUES ('RDW','Minnesota','Red Wing, MN','https://www.greatamericanstations.com/stations/red-wing-mn-rdw/','MN')
INSERT INTO [Amtrak.Station] VALUES ('SCD','Minnesota','St. Cloud, MN','https://www.greatamericanstations.com/stations/st-cloud-mn-scd/','MN')
INSERT INTO [Amtrak.Station] VALUES ('MSP','Minnesota','St. Paul-Minneapolis, MN – Union Depot','https://www.greatamericanstations.com/stations/st-paul-minneapolis-mn-msp/','MN')
INSERT INTO [Amtrak.Station] VALUES ('SPL','Minnesota','Staples, MN','https://www.greatamericanstations.com/stations/staples-mn-spl/','MN')
INSERT INTO [Amtrak.Station] VALUES ('WIN','Minnesota','Winona, MN','https://www.greatamericanstations.com/stations/winona-mn-win/','MN')
INSERT INTO [Amtrak.Station] VALUES ('BRH','Mississippi','Brookhaven, MS','https://www.greatamericanstations.com/stations/brookhaven-ms-brh/','MS')
INSERT INTO [Amtrak.Station] VALUES ('GWD','Mississippi','Greenwood, MS','https://www.greatamericanstations.com/stations/greenwood-ms-gwd/','MS')
INSERT INTO [Amtrak.Station] VALUES ('HBG','Mississippi','Hattiesburg, MS','https://www.greatamericanstations.com/stations/hattiesburg-ms-hbg/','MS')
INSERT INTO [Amtrak.Station] VALUES ('HAZ','Mississippi','Hazlehurst, MS','https://www.greatamericanstations.com/stations/hazlehurst-ms-haz/','MS')
INSERT INTO [Amtrak.Station] VALUES ('JAN','Mississippi','Jackson, MS','https://www.greatamericanstations.com/stations/jackson-ms-jan/','MS')
INSERT INTO [Amtrak.Station] VALUES ('LAU','Mississippi','Laurel, MS','https://www.greatamericanstations.com/stations/laurel-ms-lau/','MS')
INSERT INTO [Amtrak.Station] VALUES ('MKS','Mississippi','Marks, MS','https://www.greatamericanstations.com/stations/marks-ms-mks/','MS')
INSERT INTO [Amtrak.Station] VALUES ('MCB','Mississippi','McComb, MS','https://www.greatamericanstations.com/stations/mccomb-ms-mcb/','MS')
INSERT INTO [Amtrak.Station] VALUES ('MEI','Mississippi','Meridian, MS – Union Station','https://www.greatamericanstations.com/stations/meridian-ms-mei/','MS')
INSERT INTO [Amtrak.Station] VALUES ('PIC','Mississippi','Picayune, MS','https://www.greatamericanstations.com/stations/picayune-ms-pic/','MS')
INSERT INTO [Amtrak.Station] VALUES ('YAZ','Mississippi','Yazoo City, MS','https://www.greatamericanstations.com/stations/yazoo-city-ms-yaz/','MS')
INSERT INTO [Amtrak.Station] VALUES ('ACD','Missouri','Arcadia, MO','https://www.greatamericanstations.com/stations/arcadia-mo-acd/','MO')
INSERT INTO [Amtrak.Station] VALUES ('HEM','Missouri','Hermann, MO','https://www.greatamericanstations.com/stations/hermann-mo-hem/','MO')
INSERT INTO [Amtrak.Station] VALUES ('IDP','Missouri','Independence, MO','https://www.greatamericanstations.com/stations/independence-mo-idp/','MO')
INSERT INTO [Amtrak.Station] VALUES ('JEF','Missouri','Jefferson City, MO','https://www.greatamericanstations.com/stations/jefferson-city-mo-jef/','MO')
INSERT INTO [Amtrak.Station] VALUES ('KCY','Missouri','Kansas City, MO – Union Station','https://www.greatamericanstations.com/stations/kansas-city-mo-kcy/','MO')
INSERT INTO [Amtrak.Station] VALUES ('KWD','Missouri','Kirkwood, MO','https://www.greatamericanstations.com/stations/kirkwood-mo-kwd/','MO')
INSERT INTO [Amtrak.Station] VALUES ('LAP','Missouri','La Plata, MO','https://www.greatamericanstations.com/stations/la-plata-mo-lap/','MO')
INSERT INTO [Amtrak.Station] VALUES ('LEE','Missouri','Lee’s Summit, MO','https://www.greatamericanstations.com/stations/lees-summit-mo-lee/','MO')
INSERT INTO [Amtrak.Station] VALUES ('PBF','Missouri','Poplar Bluff, MO','https://www.greatamericanstations.com/stations/poplar-bluff-mo-pbf/','MO')
INSERT INTO [Amtrak.Station] VALUES ('SED','Missouri','Sedalia, MO','https://www.greatamericanstations.com/stations/sedalia-mo-sed/','MO')
INSERT INTO [Amtrak.Station] VALUES ('STL','Missouri','St. Louis, MO – Gateway Station','https://www.greatamericanstations.com/stations/st-louis-mo-stl/','MO')
INSERT INTO [Amtrak.Station] VALUES ('WAR','Missouri','Warrensburg, MO','https://www.greatamericanstations.com/stations/warrensburg-mo-war/','MO')
INSERT INTO [Amtrak.Station] VALUES ('WAH','Missouri','Washington, MO','https://www.greatamericanstations.com/stations/washington-mo-wah/','MO')
INSERT INTO [Amtrak.Station] VALUES ('BRO','Montana','Browning, MT','https://www.greatamericanstations.com/stations/browning-mt-bro/','MT')
INSERT INTO [Amtrak.Station] VALUES ('CUT','Montana','Cut Bank, MT','https://www.greatamericanstations.com/stations/cut-bank-mt-cut/','MT')
INSERT INTO [Amtrak.Station] VALUES ('GPK','Montana','East Glacier Park, MT','https://www.greatamericanstations.com/stations/east-glacier-park-mt-gpk/','MT')
INSERT INTO [Amtrak.Station] VALUES ('ESM','Montana','Essex, MT','https://www.greatamericanstations.com/stations/essex-mt-esm/','MT')
INSERT INTO [Amtrak.Station] VALUES ('GGW','Montana','Glasgow, MT','https://www.greatamericanstations.com/stations/glasgow-mt-ggw/','MT')
INSERT INTO [Amtrak.Station] VALUES ('HAV','Montana','Havre, MT','https://www.greatamericanstations.com/stations/havre-mt-hav/','MT')
INSERT INTO [Amtrak.Station] VALUES ('LIB','Montana','Libby, MT','https://www.greatamericanstations.com/stations/libby-mt-lib/','MT')
INSERT INTO [Amtrak.Station] VALUES ('MAL','Montana','Malta, MT','https://www.greatamericanstations.com/stations/malta-mt-mal/','MT')
INSERT INTO [Amtrak.Station] VALUES ('SBY','Montana','Shelby, MT','https://www.greatamericanstations.com/stations/shelby-mt-sby/','MT')
INSERT INTO [Amtrak.Station] VALUES ('WGL','Montana','West Glacier, MT','https://www.greatamericanstations.com/stations/west-glacier-mt-wgl/','MT')
INSERT INTO [Amtrak.Station] VALUES ('WFH','Montana','Whitefish, MT','https://www.greatamericanstations.com/stations/whitefish-mt-wfh/','MT')
INSERT INTO [Amtrak.Station] VALUES ('WPT','Montana','Wolf Point, MT','https://www.greatamericanstations.com/stations/wolf-point-mt-wpt/','MT')
INSERT INTO [Amtrak.Station] VALUES ('HAS','Nebraska','Hastings, NE','https://www.greatamericanstations.com/stations/hastings-ne-has/','NE')
INSERT INTO [Amtrak.Station] VALUES ('HLD','Nebraska','Holdrege, NE','https://www.greatamericanstations.com/stations/holdrege-ne-hld/','NE')
INSERT INTO [Amtrak.Station] VALUES ('LNK','Nebraska','Lincoln, NE','https://www.greatamericanstations.com/stations/lincoln-ne-lnk/','NE')
INSERT INTO [Amtrak.Station] VALUES ('MCK','Nebraska','McCook, NE','https://www.greatamericanstations.com/stations/mccook-ne-mck/','NE')
INSERT INTO [Amtrak.Station] VALUES ('OMA','Nebraska','Omaha, NE','https://www.greatamericanstations.com/stations/omaha-ne-oma/','NE')
INSERT INTO [Amtrak.Station] VALUES ('ELK','Nevada','Elko, NV','https://www.greatamericanstations.com/stations/elko-nv-elk/','NV')
INSERT INTO [Amtrak.Station] VALUES ('RNO','Nevada','Reno, NV','https://www.greatamericanstations.com/stations/reno-nv-rno/','NV')
INSERT INTO [Amtrak.Station] VALUES ('WNN','Nevada','Winnemucca, NV','https://www.greatamericanstations.com/stations/winnemucca-nv-wnn/','NV')
INSERT INTO [Amtrak.Station] VALUES ('CLA','New Hampshire','Claremont, NH','https://www.greatamericanstations.com/stations/claremont-nh-cla/','NH')
INSERT INTO [Amtrak.Station] VALUES ('DOV','New Hampshire','Dover, NH','https://www.greatamericanstations.com/stations/dover-nh-dov/','NH')
INSERT INTO [Amtrak.Station] VALUES ('DHM','New Hampshire','Durham, NH','https://www.greatamericanstations.com/stations/durham-nh-dhm/','NH')
INSERT INTO [Amtrak.Station] VALUES ('EXR','New Hampshire','Exeter, NH','https://www.greatamericanstations.com/stations/exeter-nh-exr/','NH')
INSERT INTO [Amtrak.Station] VALUES ('MET','New Jersey','Metropark, NJ','https://www.greatamericanstations.com/stations/metropark-iselin-nj-met/','NJ')
INSERT INTO [Amtrak.Station] VALUES ('NBK','New Jersey','New Brunswick, NJ','https://www.greatamericanstations.com/stations/new-brunswick-nj-nbk/','NJ')
INSERT INTO [Amtrak.Station] VALUES ('EWR','New Jersey','Newark, NJ – Liberty International Airport','https://www.greatamericanstations.com/stations/newark-airport-nj-ewr/','NJ')
INSERT INTO [Amtrak.Station] VALUES ('NWK','New Jersey','Newark, NJ – Penn Station','https://www.greatamericanstations.com/stations/newark-nj-nwk/','NJ')
INSERT INTO [Amtrak.Station] VALUES ('PJC','New Jersey','Princeton Junction, NJ','https://www.greatamericanstations.com/stations/princeton-junction-nj-pjc/','NJ')
INSERT INTO [Amtrak.Station] VALUES ('TRE','New Jersey','Trenton, NJ','https://www.greatamericanstations.com/stations/trenton-nj-tre/','NJ')
INSERT INTO [Amtrak.Station] VALUES ('ABQ','New Mexico','Albuquerque, NM','https://www.greatamericanstations.com/stations/albuquerque-nm-abq/','NM')
INSERT INTO [Amtrak.Station] VALUES ('DEM','New Mexico','Deming, NM','https://www.greatamericanstations.com/stations/deming-nm-dem/','NM')
INSERT INTO [Amtrak.Station] VALUES ('GLP','New Mexico','Gallup, NM','https://www.greatamericanstations.com/stations/gallup-nm-glp/','NM')
INSERT INTO [Amtrak.Station] VALUES ('LMY','New Mexico','Lamy, NM','https://www.greatamericanstations.com/stations/lamy-nm-lmy/','NM')
INSERT INTO [Amtrak.Station] VALUES ('LSV','New Mexico','Las Vegas, NM','https://www.greatamericanstations.com/stations/las-vegas-nm-lsv/','NM')
INSERT INTO [Amtrak.Station] VALUES ('LDB','New Mexico','Lordsburg, NM','https://www.greatamericanstations.com/stations/lordsburg-nm-ldb/','NM')
INSERT INTO [Amtrak.Station] VALUES ('RAT','New Mexico','Raton, NM','https://www.greatamericanstations.com/stations/raton-nm-rat/','NM')
INSERT INTO [Amtrak.Station] VALUES ('ALB','New York','Albany-Rensselaer, NY','https://www.greatamericanstations.com/stations/albany-rensselaer-ny-alb/','NY')
INSERT INTO [Amtrak.Station] VALUES ('AMS','New York','Amsterdam, NY','https://www.greatamericanstations.com/stations/amsterdam-ny-ams/','NY')
INSERT INTO [Amtrak.Station] VALUES ('BFX','New York','Buffalo, NY – Exchange Street Station','https://www.greatamericanstations.com/stations/buffalo-ny-bfx/','NY')
INSERT INTO [Amtrak.Station] VALUES ('BUF','New York','Buffalo, NY – Depew Station','https://www.greatamericanstations.com/stations/buffalo-depew-ny-buf/','NY')
INSERT INTO [Amtrak.Station] VALUES ('CRT','New York','Croton-Harmon, NY','https://www.greatamericanstations.com/stations/croton-harmon-ny-crt/','NY')
INSERT INTO [Amtrak.Station] VALUES ('FED','New York','Fort Edward, NY','https://www.greatamericanstations.com/stations/fort-edward-ny-fed/','NY')
INSERT INTO [Amtrak.Station] VALUES ('HUD','New York','Hudson, NY','https://www.greatamericanstations.com/stations/hudson-ny-hud/','NY')
INSERT INTO [Amtrak.Station] VALUES ('NRO','New York','New Rochelle, NY','https://www.greatamericanstations.com/stations/new-rochelle-ny-nro/','NY')
INSERT INTO [Amtrak.Station] VALUES ('NYP','New York','New York, NY – Moynihan Train Hall at Penn Station','https://www.greatamericanstations.com/stations/new-york-penn-station-ny-nyp/','NY')
INSERT INTO [Amtrak.Station] VALUES ('NFL','New York','Niagara Falls, NY','https://www.greatamericanstations.com/stations/niagara-falls-ny-nfl/','NY')
INSERT INTO [Amtrak.Station] VALUES ('PLB','New York','Plattsburgh, NY','https://www.greatamericanstations.com/stations/plattsburgh-ny-plb/','NY')
INSERT INTO [Amtrak.Station] VALUES ('POH','New York','Port Henry, NY','https://www.greatamericanstations.com/stations/port-henry-ny-poh/','NY')
INSERT INTO [Amtrak.Station] VALUES ('PRK','New York','Port Kent, NY','https://www.greatamericanstations.com/stations/port-kent-ny-prk/','NY')
INSERT INTO [Amtrak.Station] VALUES ('POU','New York','Poughkeepsie, NY','https://www.greatamericanstations.com/stations/poughkeepsie-ny-pou/','NY')
INSERT INTO [Amtrak.Station] VALUES ('RHI','New York','Rhinecliff, NY','https://www.greatamericanstations.com/stations/rhinecliff-ny-rhi/','NY')
INSERT INTO [Amtrak.Station] VALUES ('ROC','New York','Rochester, NY – Louise M. Slaughter Station','https://www.greatamericanstations.com/stations/rochester-ny-roc/','NY')
INSERT INTO [Amtrak.Station] VALUES ('ROM','New York','Rome, NY','https://www.greatamericanstations.com/stations/rome-ny-rom/','NY')
INSERT INTO [Amtrak.Station] VALUES ('RSP','New York','Rouses Point, NY','https://www.greatamericanstations.com/stations/rouses-point-ny-rsp/','NY')
INSERT INTO [Amtrak.Station] VALUES ('SAR','New York','Saratoga Springs, NY','https://www.greatamericanstations.com/stations/saratoga-springs-ny-sar/','NY')
INSERT INTO [Amtrak.Station] VALUES ('SDY','New York','Schenectady, NY','https://www.greatamericanstations.com/stations/schenectady-ny-sdy/','NY')
INSERT INTO [Amtrak.Station] VALUES ('SYR','New York','Syracuse, NY – Regional Transportation Center','https://www.greatamericanstations.com/stations/syracuse-ny-syr/','NY')
INSERT INTO [Amtrak.Station] VALUES ('FTC','New York','Ticonderoga, NY','https://www.greatamericanstations.com/stations/ticonderoga-ny-ftc/','NY')
INSERT INTO [Amtrak.Station] VALUES ('UCA','New York','Utica, NY','https://www.greatamericanstations.com/stations/utica-ny-uca/','NY')
INSERT INTO [Amtrak.Station] VALUES ('WSP','New York','Westport, NY','https://www.greatamericanstations.com/stations/westport-ny-wsp/','NY')
INSERT INTO [Amtrak.Station] VALUES ('WHL','New York','Whitehall, NY','https://www.greatamericanstations.com/stations/whitehall-ny-whl/','NY')
INSERT INTO [Amtrak.Station] VALUES ('YNY','New York','Yonkers, NY','https://www.greatamericanstations.com/stations/yonkers-ny-yny/','NY')
INSERT INTO [Amtrak.Station] VALUES ('BNC','North Carolina','Burlington, NC','https://www.greatamericanstations.com/stations/burlington-nc-bnc/','NC')
INSERT INTO [Amtrak.Station] VALUES ('CYN','North Carolina','Cary, NC','https://www.greatamericanstations.com/stations/cary-nc-cyn/','NC')
INSERT INTO [Amtrak.Station] VALUES ('CLT','North Carolina','Charlotte, NC','https://www.greatamericanstations.com/stations/charlotte-nc-clt/','NC')
INSERT INTO [Amtrak.Station] VALUES ('DNC','North Carolina','Durham, NC','https://www.greatamericanstations.com/stations/durham-nc-dnc/','NC')
INSERT INTO [Amtrak.Station] VALUES ('FAY','North Carolina','Fayetteville, NC','https://www.greatamericanstations.com/stations/fayetteville-nc-fay/','NC')
INSERT INTO [Amtrak.Station] VALUES ('GAS','North Carolina','Gastonia, NC','https://www.greatamericanstations.com/stations/gastonia-nc-gas/','NC')
INSERT INTO [Amtrak.Station] VALUES ('GRO','North Carolina','Greensboro, NC','https://www.greatamericanstations.com/stations/greensboro-nc-gro/','NC')
INSERT INTO [Amtrak.Station] VALUES ('HAM','North Carolina','Hamlet, NC','https://www.greatamericanstations.com/stations/hamlet-nc-ham/','NC')
INSERT INTO [Amtrak.Station] VALUES ('HPT','North Carolina','High Point, NC','https://www.greatamericanstations.com/stations/high-point-nc-hpt/','NC')
INSERT INTO [Amtrak.Station] VALUES ('KAN','North Carolina','Kannapolis, NC','https://www.greatamericanstations.com/stations/kannapolis-nc-kan/','NC')
INSERT INTO [Amtrak.Station] VALUES ('RGH','North Carolina','Raleigh, NC – Union Station','https://www.greatamericanstations.com/stations/raleigh-nc-rgh/','NC')
INSERT INTO [Amtrak.Station] VALUES ('RMT','North Carolina','Rocky Mount, NC','https://www.greatamericanstations.com/stations/rocky-mount-nc-rmt/','NC')
INSERT INTO [Amtrak.Station] VALUES ('SAL','North Carolina','Salisbury, NC','https://www.greatamericanstations.com/stations/salisbury-nc-sal/','NC')
INSERT INTO [Amtrak.Station] VALUES ('SSM','North Carolina','Selma-Smithfield, NC','https://www.greatamericanstations.com/stations/selma-nc-ssm/','NC')
INSERT INTO [Amtrak.Station] VALUES ('SOP','North Carolina','Southern Pines, NC','https://www.greatamericanstations.com/stations/southern-pines-nc-sop/','NC')
INSERT INTO [Amtrak.Station] VALUES ('WLN','North Carolina','Wilson, NC','https://www.greatamericanstations.com/stations/wilson-nc-wln/','NC')
INSERT INTO [Amtrak.Station] VALUES ('DVL','North Dakota','Devils Lake, ND','https://www.greatamericanstations.com/stations/devils-lake-nd-dvl/','ND')
INSERT INTO [Amtrak.Station] VALUES ('FAR','North Dakota','Fargo, ND','https://www.greatamericanstations.com/stations/fargo-nd-far/','ND')
INSERT INTO [Amtrak.Station] VALUES ('GFK','North Dakota','Grand Forks, ND','https://www.greatamericanstations.com/stations/grand-forks-nd-gfk/','ND')
INSERT INTO [Amtrak.Station] VALUES ('MOT','North Dakota','Minot, ND','https://www.greatamericanstations.com/stations/minot-nd-mot/','ND')
INSERT INTO [Amtrak.Station] VALUES ('RUG','North Dakota','Rugby, ND','https://www.greatamericanstations.com/stations/rugby-nd-rug/','ND')
INSERT INTO [Amtrak.Station] VALUES ('STN','North Dakota','Stanley, ND','https://www.greatamericanstations.com/stations/stanley-nd-stn/','ND')
INSERT INTO [Amtrak.Station] VALUES ('WTN','North Dakota','Williston, ND','https://www.greatamericanstations.com/stations/williston-nd-wtn/','ND')
INSERT INTO [Amtrak.Station] VALUES ('ALC','Ohio','Alliance, OH','https://www.greatamericanstations.com/stations/alliance-oh-alc/','OH')
INSERT INTO [Amtrak.Station] VALUES ('BYN','Ohio','Bryan, OH','https://www.greatamericanstations.com/stations/bryan-oh-byn/','OH')
INSERT INTO [Amtrak.Station] VALUES ('CIN','Ohio','Cincinnati, OH – Union Terminal','https://www.greatamericanstations.com/stations/cincinnati-oh-cin/','OH')
INSERT INTO [Amtrak.Station] VALUES ('CLE','Ohio','Cleveland, OH','https://www.greatamericanstations.com/stations/cleveland-oh-cle/','OH')
INSERT INTO [Amtrak.Station] VALUES ('ELY','Ohio','Elyria, OH','https://www.greatamericanstations.com/stations/elyria-oh-ely/','OH')
INSERT INTO [Amtrak.Station] VALUES ('SKY','Ohio','Sandusky, OH','https://www.greatamericanstations.com/stations/sandusky-oh-sky/','OH')
INSERT INTO [Amtrak.Station] VALUES ('TOL','Ohio','Toledo, OH','https://www.greatamericanstations.com/stations/toledo-oh-tol/','OH')
INSERT INTO [Amtrak.Station] VALUES ('ADM','Oklahoma','Ardmore, OK','https://www.greatamericanstations.com/stations/ardmore-ok-adm/','OK')
INSERT INTO [Amtrak.Station] VALUES ('NOR','Oklahoma','Norman, OK','https://www.greatamericanstations.com/stations/norman-ok-nor/','OK')
INSERT INTO [Amtrak.Station] VALUES ('OKC','Oklahoma','Oklahoma City, OK','https://www.greatamericanstations.com/stations/oklahoma-city-ok-okc/','OK')
INSERT INTO [Amtrak.Station] VALUES ('PVL','Oklahoma','Pauls Valley, OK','https://www.greatamericanstations.com/stations/pauls-valley-ok-pvl/','OK')
INSERT INTO [Amtrak.Station] VALUES ('PUR','Oklahoma','Purcell, OK','https://www.greatamericanstations.com/stations/purcell-ok-pur/','OK')
INSERT INTO [Amtrak.Station] VALUES ('NFS','Ontario (Canada)','Niagara Falls, ON','https://www.greatamericanstations.com/stations/niagara-falls-on-nfs/','ON')
INSERT INTO [Amtrak.Station] VALUES ('ALY','Oregon','Albany, OR','https://www.greatamericanstations.com/stations/albany-or-aly/','OR')
INSERT INTO [Amtrak.Station] VALUES ('CMO','Oregon','Chemult, OR','https://www.greatamericanstations.com/stations/chemult-or-cmo/','OR')
INSERT INTO [Amtrak.Station] VALUES ('EUG','Oregon','Eugene, OR','https://www.greatamericanstations.com/stations/eugene-or-eug/','OR')
INSERT INTO [Amtrak.Station] VALUES ('KFS','Oregon','Klamath Falls, OR','https://www.greatamericanstations.com/stations/klamath-falls-or-kfs/','OR')
INSERT INTO [Amtrak.Station] VALUES ('ORC','Oregon','Oregon City, OR','https://www.greatamericanstations.com/stations/oregon-city-or-orc/','OR')
INSERT INTO [Amtrak.Station] VALUES ('PDX','Oregon','Portland, OR – Union Station','https://www.greatamericanstations.com/stations/portland-or-pdx/','OR')
INSERT INTO [Amtrak.Station] VALUES ('SLM','Oregon','Salem, OR','https://www.greatamericanstations.com/stations/salem-or-slm/','OR')
INSERT INTO [Amtrak.Station] VALUES ('ALT','Pennsylvania','Altoona, PA','https://www.greatamericanstations.com/stations/altoona-pa-alt/','PA')
INSERT INTO [Amtrak.Station] VALUES ('ARD','Pennsylvania','Ardmore, PA','https://www.greatamericanstations.com/stations/ardmore-pa-ard/','PA')
INSERT INTO [Amtrak.Station] VALUES ('COT','Pennsylvania','Coatesville, PA','https://www.greatamericanstations.com/stations/coatesville-pa-cot/','PA')
INSERT INTO [Amtrak.Station] VALUES ('COV','Pennsylvania','Connellsville, PA','https://www.greatamericanstations.com/stations/connellsville-pa-cov/','PA')
INSERT INTO [Amtrak.Station] VALUES ('CWH','Pennsylvania','Cornwells Heights, PA','https://www.greatamericanstations.com/stations/cornwells-heights-pa-cwh/','PA')
INSERT INTO [Amtrak.Station] VALUES ('DOW','Pennsylvania','Downingtown, PA','https://www.greatamericanstations.com/stations/downingtown-pa-dow/','PA')
INSERT INTO [Amtrak.Station] VALUES ('ELT','Pennsylvania','Elizabethtown, PA','https://www.greatamericanstations.com/stations/elizabethtown-pa-elt/','PA')
INSERT INTO [Amtrak.Station] VALUES ('ERI','Pennsylvania','Erie, PA','https://www.greatamericanstations.com/stations/erie-pa-eri/','PA')
INSERT INTO [Amtrak.Station] VALUES ('EXT','Pennsylvania','Exton, PA','https://www.greatamericanstations.com/stations/exton-pa-ext/','PA')
INSERT INTO [Amtrak.Station] VALUES ('GNB','Pennsylvania','Greensburg, PA','https://www.greatamericanstations.com/stations/greensburg-pa-gnb/','PA')
INSERT INTO [Amtrak.Station] VALUES ('HAR','Pennsylvania','Harrisburg, PA','https://www.greatamericanstations.com/stations/harrisburg-pa-har/','PA')
INSERT INTO [Amtrak.Station] VALUES ('HGD','Pennsylvania','Huntingdon, PA','https://www.greatamericanstations.com/stations/huntingdon-pa-hgd/','PA')
INSERT INTO [Amtrak.Station] VALUES ('JST','Pennsylvania','Johnstown, PA','https://www.greatamericanstations.com/stations/johnstown-pa-jst/','PA')
INSERT INTO [Amtrak.Station] VALUES ('LNC','Pennsylvania','Lancaster, PA','https://www.greatamericanstations.com/stations/lancaster-pa-lnc/','PA')
INSERT INTO [Amtrak.Station] VALUES ('LAB','Pennsylvania','Latrobe, PA','https://www.greatamericanstations.com/stations/latrobe-pa-lab/','PA')
INSERT INTO [Amtrak.Station] VALUES ('LEW','Pennsylvania','Lewistown, PA','https://www.greatamericanstations.com/stations/lewistown-pa-lew/','PA')
INSERT INTO [Amtrak.Station] VALUES ('MID','Pennsylvania','Middletown, PA','https://www.greatamericanstations.com/stations/middletown-pa-mid/','PA')
INSERT INTO [Amtrak.Station] VALUES ('MJY','Pennsylvania','Mount Joy, PA','https://www.greatamericanstations.com/stations/mount-joy-pa-mjy/','PA')
INSERT INTO [Amtrak.Station] VALUES ('PHN','Pennsylvania','North Philadelphia, PA','https://www.greatamericanstations.com/stations/philadelphia-north-philadelphia-pa-phn/','PA')
INSERT INTO [Amtrak.Station] VALUES ('PAO','Pennsylvania','Paoli, PA','https://www.greatamericanstations.com/stations/paoli-pa-pao/','PA')
INSERT INTO [Amtrak.Station] VALUES ('PAR','Pennsylvania','Parkesburg, PA','https://www.greatamericanstations.com/stations/parkesburg-pa-par/','PA')
INSERT INTO [Amtrak.Station] VALUES ('PHL','Pennsylvania','Philadelphia, PA – William H. Gray III 30th Street Station','https://www.greatamericanstations.com/stations/philadelphia-pa-phl/','PA')
INSERT INTO [Amtrak.Station] VALUES ('PGH','Pennsylvania','Pittsburgh, PA – Union Station','https://www.greatamericanstations.com/stations/pittsburgh-pa-pgh/','PA')
INSERT INTO [Amtrak.Station] VALUES ('TYR','Pennsylvania','Tyrone, PA','https://www.greatamericanstations.com/stations/tyrone-pa-tyr/','PA')
INSERT INTO [Amtrak.Station] VALUES ('MTR','Quebec (Canada)','Montreal, QC – Gare Centrale / Central Station','https://www.greatamericanstations.com/stations/montreal-qc-mtr/','QE')
INSERT INTO [Amtrak.Station] VALUES ('SLQ','Quebec (Canada)','St-Lambert, QC','https://www.greatamericanstations.com/stations/st-lambert-qc-slq/','QE')
INSERT INTO [Amtrak.Station] VALUES ('KIN','Rhode Island','Kingston, RI','https://www.greatamericanstations.com/stations/kingston-ri-kin/','RI')
INSERT INTO [Amtrak.Station] VALUES ('PVD','Rhode Island','Providence, RI','https://www.greatamericanstations.com/stations/providence-ri-pvd/','RI')
INSERT INTO [Amtrak.Station] VALUES ('WLY','Rhode Island','Westerly, RI','https://www.greatamericanstations.com/stations/westerly-ri-wly/','RI')
INSERT INTO [Amtrak.Station] VALUES ('CAM','South Carolina','Camden, SC','https://www.greatamericanstations.com/stations/camden-sc-cam/','SC')
INSERT INTO [Amtrak.Station] VALUES ('CHS','South Carolina','Charleston, SC','https://www.greatamericanstations.com/stations/charleston-sc-chs/','SC')
INSERT INTO [Amtrak.Station] VALUES ('CSN','South Carolina','Clemson, SC','https://www.greatamericanstations.com/stations/clemson-sc-csn/','SC')
INSERT INTO [Amtrak.Station] VALUES ('CLB','South Carolina','Columbia, SC','https://www.greatamericanstations.com/stations/columbia-sc-clb/','SC')
INSERT INTO [Amtrak.Station] VALUES ('DNK','South Carolina','Denmark, SC','https://www.greatamericanstations.com/stations/denmark-sc-dnk/','SC')
INSERT INTO [Amtrak.Station] VALUES ('DIL','South Carolina','Dillon, SC','https://www.greatamericanstations.com/stations/dillon-sc-dil/','SC')
INSERT INTO [Amtrak.Station] VALUES ('FLO','South Carolina','Florence, SC','https://www.greatamericanstations.com/stations/florence-sc-flo/','SC')
INSERT INTO [Amtrak.Station] VALUES ('GRV','South Carolina','Greenville, SC','https://www.greatamericanstations.com/stations/greenville-sc-grv/','SC')
INSERT INTO [Amtrak.Station] VALUES ('KTR','South Carolina','Kingstree, SC','https://www.greatamericanstations.com/stations/kingstree-sc-ktr/','SC')
INSERT INTO [Amtrak.Station] VALUES ('SPB','South Carolina','Spartanburg, SC','https://www.greatamericanstations.com/stations/spartanburg-sc-spb/','SC')
INSERT INTO [Amtrak.Station] VALUES ('YEM','South Carolina','Yemassee, SC','https://www.greatamericanstations.com/stations/yemassee-sc-yem/','SC')
INSERT INTO [Amtrak.Station] VALUES ('MEM','Tennessee','Memphis, TN – Central Station','https://www.greatamericanstations.com/stations/memphis-tn-mem/','TN')
INSERT INTO [Amtrak.Station] VALUES ('NBN','Tennessee','Newbern – Dyersburg, TN','https://www.greatamericanstations.com/stations/newbern-tn-nbn/','TN')
INSERT INTO [Amtrak.Station] VALUES ('ALP','Texas','Alpine, TX','https://www.greatamericanstations.com/stations/alpine-tx-alp/','TX')
INSERT INTO [Amtrak.Station] VALUES ('AUS','Texas','Austin, TX','https://www.greatamericanstations.com/stations/austin-tx-aus/','TX')
INSERT INTO [Amtrak.Station] VALUES ('BMT','Texas','Beaumont, TX','https://www.greatamericanstations.com/stations/beaumont-tx-bmt/','TX')
INSERT INTO [Amtrak.Station] VALUES ('CBR','Texas','Cleburne, TX','https://www.greatamericanstations.com/stations/cleburne-tx-cbr/','TX')
INSERT INTO [Amtrak.Station] VALUES ('DAL','Texas','Dallas, TX – Eddie Bernice Johnson Union Station','https://www.greatamericanstations.com/stations/dallas-tx-dal/','TX')
INSERT INTO [Amtrak.Station] VALUES ('DRT','Texas','Del Rio, TX','https://www.greatamericanstations.com/stations/del-rio-tx-drt/','TX')
INSERT INTO [Amtrak.Station] VALUES ('ELP','Texas','El Paso, TX – Union Depot','https://www.greatamericanstations.com/stations/el-paso-tx-elp/','TX')
INSERT INTO [Amtrak.Station] VALUES ('FTW','Texas','Fort Worth, TX','https://www.greatamericanstations.com/stations/fort-worth-tx-ftw/','TX')
INSERT INTO [Amtrak.Station] VALUES ('GLE','Texas','Gainesville, TX','https://www.greatamericanstations.com/stations/gainesville-tx-gle/','TX')
INSERT INTO [Amtrak.Station] VALUES ('HOS','Texas','Houston, TX','https://www.greatamericanstations.com/stations/houston-tx-hos/','TX')
INSERT INTO [Amtrak.Station] VALUES ('LVW','Texas','Longview, TX','https://www.greatamericanstations.com/stations/longview-tx-lvw/','TX')
INSERT INTO [Amtrak.Station] VALUES ('MHL','Texas','Marshall, TX','https://www.greatamericanstations.com/stations/marshall-tx-mhl/','TX')
INSERT INTO [Amtrak.Station] VALUES ('MCG','Texas','McGregor, TX','https://www.greatamericanstations.com/stations/mcgregor-tx-mcg/','TX')
INSERT INTO [Amtrak.Station] VALUES ('MIN','Texas','Mineola, TX','https://www.greatamericanstations.com/stations/mineola-tx-min/','TX')
INSERT INTO [Amtrak.Station] VALUES ('SAS','Texas','San Antonio, TX','https://www.greatamericanstations.com/stations/san-antonio-tx-sas/','TX')
INSERT INTO [Amtrak.Station] VALUES ('SMC','Texas','San Marcos, TX','https://www.greatamericanstations.com/stations/san-marcos-tx-smc/','TX')
INSERT INTO [Amtrak.Station] VALUES ('SND','Texas','Sanderson, TX','https://www.greatamericanstations.com/stations/sanderson-tx-snd/','TX')
INSERT INTO [Amtrak.Station] VALUES ('TAY','Texas','Taylor, TX','https://www.greatamericanstations.com/stations/taylor-tx-tay/','TX')
INSERT INTO [Amtrak.Station] VALUES ('TPL','Texas','Temple, TX','https://www.greatamericanstations.com/stations/temple-tx-tpl/','TX')
INSERT INTO [Amtrak.Station] VALUES ('GRI','Utah','Green River, UT','https://www.greatamericanstations.com/stations/green-river-ut-gri/','UT')
INSERT INTO [Amtrak.Station] VALUES ('HER','Utah','Helper, UT','https://www.greatamericanstations.com/stations/helper-ut-her/','UT')
INSERT INTO [Amtrak.Station] VALUES ('PRO','Utah','Provo, UT','https://www.greatamericanstations.com/stations/provo-ut-pro/','UT')
INSERT INTO [Amtrak.Station] VALUES ('SLC','Utah','Salt Lake City, UT','https://www.greatamericanstations.com/stations/salt-lake-city-ut-slc/','UT')
INSERT INTO [Amtrak.Station] VALUES ('BLF','Vermont','Bellows Falls, VT','https://www.greatamericanstations.com/stations/bellows-falls-vt-blf/','VT')
INSERT INTO [Amtrak.Station] VALUES ('BRA','Vermont','Brattleboro, VT','https://www.greatamericanstations.com/stations/brattleboro-vt-bra/','VT')
INSERT INTO [Amtrak.Station] VALUES ('BTN','Vermont','Burlington, VT','https://www.greatamericanstations.com/stations/burlington-vt-btn/','VT')
INSERT INTO [Amtrak.Station] VALUES ('CNV','Vermont','Castleton, VT','https://www.greatamericanstations.com/stations/castleton-vt-cnv/','VT')
INSERT INTO [Amtrak.Station] VALUES ('ESX','Vermont','Essex Junction-Burlington, VT','https://www.greatamericanstations.com/stations/essex-jct-vt-esx/','VT')
INSERT INTO [Amtrak.Station] VALUES ('VRN','Vermont','Ferrisburgh-Vergennes','https://www.greatamericanstations.com/stations/ferrisburgh-vergennes-vt-vrn/','VT')
INSERT INTO [Amtrak.Station] VALUES ('MBY','Vermont','Middlebury, VT','https://www.greatamericanstations.com/stations/middlebury-vt-mby/','VT')
INSERT INTO [Amtrak.Station] VALUES ('MPR','Vermont','Montpelier-Berlin, VT','https://www.greatamericanstations.com/stations/montpelier-berlin-vt-mpr/','VT')
INSERT INTO [Amtrak.Station] VALUES ('RPH','Vermont','Randolph, VT','https://www.greatamericanstations.com/stations/randolph-vt-rph/','VT')
INSERT INTO [Amtrak.Station] VALUES ('RUD','Vermont','Rutland, VT','https://www.greatamericanstations.com/stations/rutland-vt-rud/','VT')
INSERT INTO [Amtrak.Station] VALUES ('SAB','Vermont','St. Albans, VT','https://www.greatamericanstations.com/stations/st-albans-vt-sab/','VT')
INSERT INTO [Amtrak.Station] VALUES ('WAB','Vermont','Waterbury-Stowe, VT','https://www.greatamericanstations.com/stations/waterbury-vt-wab/','VT')
INSERT INTO [Amtrak.Station] VALUES ('WRJ','Vermont','White River Junction, VT','https://www.greatamericanstations.com/stations/white-river-junction-vt-wrj/','VT')
INSERT INTO [Amtrak.Station] VALUES ('WNM','Vermont','Windsor-Mt. Ascutney, VT','https://www.greatamericanstations.com/stations/windsor-vt-wnm/','VT')
INSERT INTO [Amtrak.Station] VALUES ('ALX','Virginia','Alexandria, VA','https://www.greatamericanstations.com/stations/alexandria-va-alx/','VA')
INSERT INTO [Amtrak.Station] VALUES ('ASD','Virginia','Ashland, VA','https://www.greatamericanstations.com/stations/ashland-va-asd/','VA')
INSERT INTO [Amtrak.Station] VALUES ('BCV','Virginia','Burke Centre, VA','https://www.greatamericanstations.com/stations/burke-centre-va-bcv/','VA')
INSERT INTO [Amtrak.Station] VALUES ('CVS','Virginia','Charlottesville, VA','https://www.greatamericanstations.com/stations/charlottesville-va-cvs/','VA')
INSERT INTO [Amtrak.Station] VALUES ('CLF','Virginia','Clifton Forge, VA','https://www.greatamericanstations.com/stations/clifton-forge-va-clf/','VA')
INSERT INTO [Amtrak.Station] VALUES ('CLP','Virginia','Culpeper, VA','https://www.greatamericanstations.com/stations/culpeper-va-clp/','VA')
INSERT INTO [Amtrak.Station] VALUES ('DAN','Virginia','Danville, VA','https://www.greatamericanstations.com/stations/danville-va-dan/','VA')
INSERT INTO [Amtrak.Station] VALUES ('FBG','Virginia','Fredericksburg, VA','https://www.greatamericanstations.com/stations/fredericksburg-va-fbg/','VA')
INSERT INTO [Amtrak.Station] VALUES ('LOR','Virginia','Lorton, VA – Auto Train Station','https://www.greatamericanstations.com/stations/lorton-va-lor/','VA')
INSERT INTO [Amtrak.Station] VALUES ('LYH','Virginia','Lynchburg, VA','https://www.greatamericanstations.com/stations/lynchburg-va-lyh/','VA')
INSERT INTO [Amtrak.Station] VALUES ('MSS','Virginia','Manassas, VA','https://www.greatamericanstations.com/stations/manassas-va-mss/','VA')
INSERT INTO [Amtrak.Station] VALUES ('NPN','Virginia','Newport News, VA','https://www.greatamericanstations.com/stations/newport-news-va-npn/','VA')
INSERT INTO [Amtrak.Station] VALUES ('NFK','Virginia','Norfolk, VA','https://www.greatamericanstations.com/stations/norfolk-va-nfk/','VA')
INSERT INTO [Amtrak.Station] VALUES ('PTB','Virginia','Petersburg, VA','https://www.greatamericanstations.com/stations/petersburg-va-ptb/','VA')
INSERT INTO [Amtrak.Station] VALUES ('QAN','Virginia','Quantico, VA','https://www.greatamericanstations.com/stations/quantico-va-qan/','VA')
INSERT INTO [Amtrak.Station] VALUES ('RVM','Virginia','Richmond, VA – Main Street Station','https://www.greatamericanstations.com/stations/richmond-main-street-station-va-rvm/','VA')
INSERT INTO [Amtrak.Station] VALUES ('RVR','Virginia','Richmond, VA – Staples Mill Road Station','https://www.greatamericanstations.com/stations/richmond-staples-mill-road-station-va-rvr/','VA')
INSERT INTO [Amtrak.Station] VALUES ('RNK','Virginia','Roanoke, VA','https://www.greatamericanstations.com/stations/roanoke-va-rnk/','VA')
INSERT INTO [Amtrak.Station] VALUES ('STA','Virginia','Staunton, VA','https://www.greatamericanstations.com/stations/staunton-va-sta/','VA')
INSERT INTO [Amtrak.Station] VALUES ('WBG','Virginia','Williamsburg, VA','https://www.greatamericanstations.com/stations/williamsburg-va-wbg/','VA')
INSERT INTO [Amtrak.Station] VALUES ('WDB','Virginia','Woodbridge, VA','https://www.greatamericanstations.com/stations/woodbridge-va-wdb/','VA')
INSERT INTO [Amtrak.Station] VALUES ('BEL','Washington','Bellingham, WA','https://www.greatamericanstations.com/stations/bellingham-wa-bel/','WA')
INSERT INTO [Amtrak.Station] VALUES ('BNG','Washington','Bingen-White Salmon, WA','https://www.greatamericanstations.com/stations/bingen-white-salmon-wa-bng/','WA')
INSERT INTO [Amtrak.Station] VALUES ('CTL','Washington','Centralia, WA','https://www.greatamericanstations.com/stations/centralia-wa-ctl/','WA')
INSERT INTO [Amtrak.Station] VALUES ('EDM','Washington','Edmonds, WA','https://www.greatamericanstations.com/stations/edmonds-wa-edm/','WA')
INSERT INTO [Amtrak.Station] VALUES ('EPH','Washington','Ephrata, WA','https://www.greatamericanstations.com/stations/ephrata-wa-eph/','WA')
INSERT INTO [Amtrak.Station] VALUES ('EVR','Washington','Everett, WA','https://www.greatamericanstations.com/stations/everett-wa-evr/','WA')
INSERT INTO [Amtrak.Station] VALUES ('KEL','Washington','Kelso-Longview, WA','https://www.greatamericanstations.com/stations/kelso-longview-wa-kel/','WA')
INSERT INTO [Amtrak.Station] VALUES ('LWA','Washington','Leavenworth, WA – Icicle Station','https://www.greatamericanstations.com/stations/leavenworth-wa-lwa/','WA')
INSERT INTO [Amtrak.Station] VALUES ('MVW','Washington','Mount Vernon, WA','https://www.greatamericanstations.com/stations/mount-vernon-wa-mvw/','WA')
INSERT INTO [Amtrak.Station] VALUES ('OLW','Washington','Olympia-Lacey, WA','https://www.greatamericanstations.com/stations/olympia-lacey-wa-olw/','WA')
INSERT INTO [Amtrak.Station] VALUES ('PSC','Washington','Pasco, WA','https://www.greatamericanstations.com/stations/pasco-wa-psc/','WA')
INSERT INTO [Amtrak.Station] VALUES ('SEA','Washington','Seattle, WA – King Street Station','https://www.greatamericanstations.com/stations/seattle-wa-sea/','WA')
INSERT INTO [Amtrak.Station] VALUES ('SPK','Washington','Spokane, WA','https://www.greatamericanstations.com/stations/spokane-wa-spk/','WA')
INSERT INTO [Amtrak.Station] VALUES ('STW','Washington','Stanwood, WA','https://www.greatamericanstations.com/stations/stanwood-wa-stw/','WA')
INSERT INTO [Amtrak.Station] VALUES ('TAC','Washington','Tacoma, WA','https://www.greatamericanstations.com/stations/tacoma-wa-tac/','WA')
INSERT INTO [Amtrak.Station] VALUES ('TUK','Washington','Tukwila, WA','https://www.greatamericanstations.com/stations/tukwila-wa-tuk/','WA')
INSERT INTO [Amtrak.Station] VALUES ('VAN','Washington','Vancouver, WA','https://www.greatamericanstations.com/stations/vancouver-wa-van/','WA')
INSERT INTO [Amtrak.Station] VALUES ('WEN','Washington','Wenatchee, WA','https://www.greatamericanstations.com/stations/wenatchee-wa-wen/','WA')
INSERT INTO [Amtrak.Station] VALUES ('WIH','Washington','Wishram, WA','https://www.greatamericanstations.com/stations/wishram-wa-wih/','WA')
INSERT INTO [Amtrak.Station] VALUES ('ALD','West Virginia','Alderson, WV','https://www.greatamericanstations.com/stations/alderson-wv-ald/','WV')
INSERT INTO [Amtrak.Station] VALUES ('CHW','West Virginia','Charleston, WV','https://www.greatamericanstations.com/stations/charleston-wv-chw/','WV')
INSERT INTO [Amtrak.Station] VALUES ('HFY','West Virginia','Harpers Ferry, WV','https://www.greatamericanstations.com/stations/harpers-ferry-wv-hfy/','WV')
INSERT INTO [Amtrak.Station] VALUES ('HIN','West Virginia','Hinton, WV','https://www.greatamericanstations.com/stations/hinton-wv-hin/','WV')
INSERT INTO [Amtrak.Station] VALUES ('HUN','West Virginia','Huntington, WV','https://www.greatamericanstations.com/stations/huntington-wv-hun/','WV')
INSERT INTO [Amtrak.Station] VALUES ('MRB','West Virginia','Martinsburg, WV','https://www.greatamericanstations.com/stations/martinsburg-wv-mrb/','WV')
INSERT INTO [Amtrak.Station] VALUES ('MNG','West Virginia','Montgomery, WV','https://www.greatamericanstations.com/stations/montgomery-wv-mng/','WV')
INSERT INTO [Amtrak.Station] VALUES ('PRC','West Virginia','Prince, WV','https://www.greatamericanstations.com/stations/prince-wv-prc/','WV')
INSERT INTO [Amtrak.Station] VALUES ('THN','West Virginia','Thurmond, WV','https://www.greatamericanstations.com/stations/thurmond-wv-thn/','WV')
INSERT INTO [Amtrak.Station] VALUES ('WSS','West Virginia','White Sulphur Springs, WV','https://www.greatamericanstations.com/stations/white-sulphur-springs-wv-wss/','WV')
INSERT INTO [Amtrak.Station] VALUES ('CBS','Wisconsin','Columbus, WI','https://www.greatamericanstations.com/stations/columbus-wi-cbs/','WI')
INSERT INTO [Amtrak.Station] VALUES ('LSE','Wisconsin','La Crosse, WI','https://www.greatamericanstations.com/stations/la-crosse-wi-lse/','WI')
INSERT INTO [Amtrak.Station] VALUES ('MKA','Wisconsin','Milwaukee, WI – General Mitchell International Airport','https://www.greatamericanstations.com/stations/milwaukee-general-mitchell-international-airport-wi-mka/','WI')
INSERT INTO [Amtrak.Station] VALUES ('MKE','Wisconsin','Milwaukee, WI – Downtown','https://www.greatamericanstations.com/stations/milwaukee-wi-mke/','WI')
INSERT INTO [Amtrak.Station] VALUES ('POG','Wisconsin','Portage, WI','https://www.greatamericanstations.com/stations/portage-wi-pog/','WI')
INSERT INTO [Amtrak.Station] VALUES ('SVT','Wisconsin','Sturtevant, WI','https://www.greatamericanstations.com/stations/sturtevant-wi-svt/','WI')
INSERT INTO [Amtrak.Station] VALUES ('TOH','Wisconsin','Tomah, WI','https://www.greatamericanstations.com/stations/tomah-wi-toh/','WI')
INSERT INTO [Amtrak.Station] VALUES ('WDL','Wisconsin','Wisconsin Dells, WI','https://www.greatamericanstations.com/stations/wisconsin-dells-wi-wdl/','WI')

INSERT INTO [Amtrak.Station] VALUES ('CNL','California','Col. Allensworth Park (CNL)','','CA')
INSERT INTO [Amtrak.Station] VALUES ('NAP','California','Napa (NAP)','','CA')
INSERT INTO [Amtrak.Station] VALUES ('PTC','California','Petaluma (PTC)','','CA')
INSERT INTO [Amtrak.Station] VALUES ('PCV','California','Placerville (PCV)','','CA')
INSERT INTO [Amtrak.Station] VALUES ('RPC','California','Rohnert Park (RPC)','','CA')
INSERT INTO [Amtrak.Station] VALUES ('SFC','California','San Francisco (SFC)','','CA')
INSERT INTO [Amtrak.Station] VALUES ('SRC','California','Santa Rosa (SRC)','','CA')
INSERT INTO [Amtrak.Station] VALUES ('SLV','California','Solvang (SLV)','','CA')
INSERT INTO [Amtrak.Station] VALUES ('SLT','California','South Lake Tahoe (SLT)','','CA')
INSERT INTO [Amtrak.Station] VALUES ('VAL','California','Vallejo (VAL)','','CA')
INSERT INTO [Amtrak.Station] VALUES ('LAK','Florida','Lakeland (LKL & LAK)','','FL')
INSERT INTO [Amtrak.Station] VALUES ('MCI','Indiana','Michigan City (MCI)','','IN')
INSERT INTO [Amtrak.Station] VALUES ('NYF','New York','New York State Fair (NYF)','','NY')