USE BUDT703_Project_0506_14;

--State
INSERT INTO [Amtrak.State] VALUES ('AL','Alabama')
INSERT INTO [Amtrak.State] VALUES ('AZ','Arizona')
INSERT INTO [Amtrak.State] VALUES ('AR','Arkansas')
INSERT INTO [Amtrak.State] VALUES ('BC','British Columbia (Canada)')
INSERT INTO [Amtrak.State] VALUES ('CA','California')
INSERT INTO [Amtrak.State] VALUES ('CO','Colorado')
INSERT INTO [Amtrak.State] VALUES ('CT','Connecticut')
INSERT INTO [Amtrak.State] VALUES ('DE','Delaware')
INSERT INTO [Amtrak.State] VALUES ('DC','District of Columbia')
INSERT INTO [Amtrak.State] VALUES ('FL','Florida')
INSERT INTO [Amtrak.State] VALUES ('GA','Georgia')
INSERT INTO [Amtrak.State] VALUES ('ID','Idaho')
INSERT INTO [Amtrak.State] VALUES ('IL','Illinois')
INSERT INTO [Amtrak.State] VALUES ('IN','Indiana')
INSERT INTO [Amtrak.State] VALUES ('IA','Iowa')
INSERT INTO [Amtrak.State] VALUES ('KS','Kansas')
INSERT INTO [Amtrak.State] VALUES ('KY','Kentucky')
INSERT INTO [Amtrak.State] VALUES ('LA','Louisiana')
INSERT INTO [Amtrak.State] VALUES ('ME','Maine')
INSERT INTO [Amtrak.State] VALUES ('MD','Maryland')
INSERT INTO [Amtrak.State] VALUES ('MA','Massachusetts')
INSERT INTO [Amtrak.State] VALUES ('MI','Michigan')
INSERT INTO [Amtrak.State] VALUES ('MN','Minnesota')
INSERT INTO [Amtrak.State] VALUES ('MS','Mississippi')
INSERT INTO [Amtrak.State] VALUES ('MO','Missouri')
INSERT INTO [Amtrak.State] VALUES ('MT','Montana')
INSERT INTO [Amtrak.State] VALUES ('NE','Nebraska')
INSERT INTO [Amtrak.State] VALUES ('NV','Nevada')
INSERT INTO [Amtrak.State] VALUES ('NH','New Hampshire')
INSERT INTO [Amtrak.State] VALUES ('NJ','New Jersey')
INSERT INTO [Amtrak.State] VALUES ('NM','New Mexico')
INSERT INTO [Amtrak.State] VALUES ('NY','New York')
INSERT INTO [Amtrak.State] VALUES ('NC','North Carolina')
INSERT INTO [Amtrak.State] VALUES ('ND','North Dakota')
INSERT INTO [Amtrak.State] VALUES ('OH','Ohio')
INSERT INTO [Amtrak.State] VALUES ('OK','Oklahoma')
INSERT INTO [Amtrak.State] VALUES ('ON','Ontario (Canada)')
INSERT INTO [Amtrak.State] VALUES ('OR','Oregon')
INSERT INTO [Amtrak.State] VALUES ('PA','Pennsylvania')
INSERT INTO [Amtrak.State] VALUES ('QE','Quebec (Canada)')
INSERT INTO [Amtrak.State] VALUES ('RI','Rhode Island')
INSERT INTO [Amtrak.State] VALUES ('SC','South Carolina')
INSERT INTO [Amtrak.State] VALUES ('TN','Tennessee')
INSERT INTO [Amtrak.State] VALUES ('TX','Texas')
INSERT INTO [Amtrak.State] VALUES ('UT','Utah')
INSERT INTO [Amtrak.State] VALUES ('VT','Vermont')
INSERT INTO [Amtrak.State] VALUES ('VA','Virginia')
INSERT INTO [Amtrak.State] VALUES ('WA','Washington')
INSERT INTO [Amtrak.State] VALUES ('WV','West Virginia')
INSERT INTO [Amtrak.State] VALUES ('WI','Wisconsin');
